"""add document title and study session timestamps

Revision ID: 079e35083347
Revises: d5202eeffbcc
Create Date: 2026-08-29 22:44:13.368679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079e35083347'
down_revision: Union[str, Sequence[str], None] = 'd5202eeffbcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    `title` is nullable because documents uploaded before this column existed have no
    title, and the upload field it comes from is optional anyway.

    The two timestamps are NOT NULL but safe to add to a populated table: `server_default`
    backfills every existing row with the migration's own transaction time. Without it,
    adding a NOT NULL column to a non-empty table would fail.
    """
    op.add_column('documents', sa.Column('title', sa.String(), nullable=True))
    op.add_column('study_sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('study_sessions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_sessions', 'updated_at')
    op.drop_column('study_sessions', 'created_at')
    op.drop_column('documents', 'title')
    # ### end Alembic commands ###
