"""add document status

Revision ID: c1e4a9b7f20d
Revises: d26c56635e35
Create Date: 2026-09-13 10:12:44.903118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e4a9b7f20d'
down_revision: Union[str, Sequence[str], None] = 'd26c56635e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    NOT NULL but safe to add to a populated table: `server_default` backfills every
    existing row as 'finalized', which is accurate — every document that predates this
    column completed the whole ingestion pipeline, questions included. Only review mode
    (docs/specs/2026-09-12-graph-review-mode-design.md) ever writes 'draft'.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.String(), server_default='finalized', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
