"""add document created_at

Revision ID: d26c56635e35
Revises: 079e35083347
Create Date: 2026-09-08 12:38:57.171855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26c56635e35'
down_revision: Union[str, Sequence[str], None] = '079e35083347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    NOT NULL but safe to add to a populated table: `server_default` backfills every
    existing row with the migration's own transaction time, same as the study_sessions
    timestamps added in 079e35083347.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'created_at')
    # ### end Alembic commands ###
